name: ecz_hynms
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.1+27 # Update version code to 3

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.3.11
  share_plus: ^7.2.2
  package_info: ^2.0.2
  shared_preferences: ^2.2.3
  flutter_tts: ^4.0.2
  yaml: ^3.1.2
  url_launcher: ^6.3.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true     
  ios: true
  image_path: "assets/images/hymns.png"
  adaptive_icon_background: "assets/images/hymns_background.png"
  adaptive_icon_foreground:  "assets/images/hymns_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#004d73"
  image: assets/images/hymnSplash.png
  image_dark: assets/images/hymnSplash.png

  android_12:
    color: "#004d73"
    image: assets/images/hymnSplash.png
    image_dark: assets/images/hymnSplash.png

  web: false